# -*- coding: utf-8 -*-
"""5-1.doc2vec.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q08BEj81xBXTG_uTdY1QCPeKHV-7Z_sM
"""

# https://radimrehurek.com/gensim/models/doc2vec.html
from gensim.test.utils import common_texts
from gensim.models.doc2vec import Doc2Vec, TaggedDocument

common_texts

documents = [TaggedDocument(doc, [i]) for i, doc in enumerate(common_texts)]
documents

model = Doc2Vec(documents, vector_size=5, window=3, min_count=1)

word2idx = {w:obj.index for w, obj in model.wv.vocab.items()}
idx2word = {v:k for k, v in word2idx.items()}

print("사전 크기 =", len(word2idx))
print(word2idx)

# The number of trained document tags is available from:
len(model.docvecs)

model.docvecs[[8][0]]

for text, tags in documents:
    print(model.docvecs[tags[0]])

new_doc = model.infer_vector(["system", "response"])
new_doc

model.docvecs.most_similar([new_doc], topn=3)

new_doc = model.infer_vector(['survey', 'user', 'computer', 'system', 'response', 'time'])
model.docvecs.most_similar([new_doc], topn=3)

