# -*- coding: utf-8 -*-
"""p60_.HashingVectorizer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T9kZHM4r3dAPuwyi4M8NmOiXrhbh4PZr
"""

from sklearn.feature_extraction.text import HashingVectorizer

text_data = ['나는 배가 고프다', 
             '내일 점심 뭐먹지',
             '내일 공부 해야겠다',
             '점심 먹고 공부 해야지']

hash_vectorizer = HashingVectorizer(n_features=10)
hash_vectorizer.fit(text_data)
# print(hash_vectorizer.vocabulary_)

sentence = [text_data[0]]
print(hash_vectorizer.transform(sentence).toarray())

print(hash_vectorizer.transform(text_data).toarray())

hash('나는') % 100

hash('배가') % 100

hash('고프다') % 100

hash('laskdjflk') % 100

