# -*- coding: utf-8 -*-
"""mnist.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sf5tDCQ6n6QnZZnQOt3Sqoa23sIDW0v4
"""

import numpy as np
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import pickle
import matplotlib.pyplot as plt

DATA_PATH = '/content/drive/MyDrive/Colab Notebooks/data/'

# mnist 데이터를 다운로드하고 나중에 사용하기 위해 저장해 둔다.
# 시간이 오래 걸리기 때문.
# mnist = fetch_openml('mnist_784')
# with open(DATA_PATH + 'mnist.pkl', 'wb') as f:
#        pickle.dump(mnist, f)

# 저장된 mnist 데이터를 읽어온다.
with open(DATA_PATH + 'mnist.pkl', 'rb') as f:
        mnist = pickle.load(f)

print(mnist.keys())

type(mnist['data'])

# 데이터가 많아 시간이 오래걸리므로, 앞 부분 10000개만 분석한다.
x_feat = np.array(mnist['data'][:10000])
y_target = np.array(mnist['target'][:10000])

# n-번째 손글씨 이미지를 확인해 본다.
n = 0
img = x_feat[n].reshape(28,28)
print('\nclass =', y_target[n])
plt.imshow(img)
plt.show()