# -*- coding: utf-8 -*-
"""4-8.dim_reduction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Guj4wzPc0cxswKf9HEDGNPTCAhpIuNNA
"""

from sklearn.datasets import load_breast_cancer
from sklearn.decomposition import PCA
from sklearn.decomposition import KernelPCA
from sklearn.decomposition import TruncatedSVD

# breast cancer 데이터를 가져온다.
cancer = load_breast_cancer()
x = cancer['data']
x.shape

print(x[:3, :])

# 1. PCA
# ------
pca = PCA(n_components=2)
x_pca = pca.fit_transform(x)
x_pca.shape

print(x_pca[:10, :])

# 2. KernelPCA
# ------------
kpc = KernelPCA(n_components=2)
x_kpc = kpc.fit_transform(x)
x_kpc.shape

print(x_kpc[:10, :])

# 2. SVD
# ------
svd = TruncatedSVD(n_components=2)
x_svd = svd.fit_transform(x)
x_svd.shape

print(x_svd[:10, :])

