# -*- coding: utf-8 -*-
"""p70_.nltk(pos).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/183-FrdFXa0k_OPsOJqJ5hpDxEtYbgXh9
"""

# Part of Speech tagging (POS tag)
import nltk
nltk.download('punkt')      # '/root/nltk_data/tokenizers'
nltk.download('averaged_perceptron_tagger')  # 형태소 분석을 위해 필요한 도구

sentence = """
Natural language processing (NLP) is a subfield of computer science, information engineering, 
and artificial intelligence concerned with the interactions between computers and human (natural) languages, 
in particular how to program computers to process and analyze large amounts of natural language data.
"""
word_tok = nltk.word_tokenize(sentence)
print(word_tok)

nltk.pos_tag(word_tok)

# 명사와 형용사만 표시한다.
sent_nnjj = [word for word, pos in nltk.pos_tag(word_tok) if pos == 'NN' or pos == 'JJ']
sent_nnjj

# bigram
bigram = [(a, b) for a, b in nltk.bigrams(sent_nnjj)]
bigram

# trigram
trigram = [(a, b, c) for a, b, c in nltk.trigrams(sent_nnjj)]
trigram

# n-gram
ngram = [(a, b, c, d) for a, b, c, d in nltk.ngrams(sent_nnjj, 4)]
ngram

