# -*- coding: utf-8 -*-
"""8-5.Pororo_NER.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-4Qm3BhC86T4MyLB3fHfRs4ed-HgpBMV
"""

# 카카오브레인의 통합 자연어 프레임워크
# 카카오브레인에서 다양한 자연어 태스크에 대응 가능한 통합된 형태의 자연어 프레임워크인 Pororo를 오픈소스로 공개했습니다.
# Pororo는 Platform Of neuRal mOdels for natuRal language prOcessing의 약자이며 HuggingFace와 유사한 목적이라고 생각할 수 
# 있습니다. Pororo는 한국어 태스크들에 대해 좀 더 최적화 되어 있을 뿐 아니라 음성 인식 등 오디오 처리도 함께 지원한다는 장점이 있습니다.
# https://github.com/kakaobrain/pororo
!pip install pororo

from pororo import Pororo

ner = Pororo(task="ner", lang="ko")

str = '美올랜드 병원 최악 총기 테러 부상자 치료비 안 받는다'
print(ner(str))

str = '대한민국에는 美인이 많다.'
print(ner(str))

str = '美國은 영토가 넓다.'
print(ner(str))

str = '대한민국에는 美人이 많다.'
print(ner(str))

str = '美남부에는 목화 농장이 많았다.'
print(ner(str))

str = '美남부에는 목화 목장이 많았다.'
print(ner(str))

str = '목화 꽃이 만발하다.'
print(ner(str))

str = '목화밭에 가보고 싶다.'
print(ner(str))

str = '美올랜드 병원 최악 총기 테러 부상자 치료비 안 받는다'

word_tag = []
for word, tag in ner(str):
    if word != ' ':
        word = word.replace(' ', '_')
        if tag != 'O':
            word_tag.append(word + '_' + tag[:3])
        else:
            word_tag.append(word)

print(word_tag)
print(' '.join(word_tag))

