# -*- coding: utf-8 -*-
"""4.ffn(mnist_2D).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QK6_j6AbQbpEQmAGyx9RdJ9-zN7LQaGM
"""

from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Model
from tensorflow.keras import optimizers
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import numpy as np
import pickle

# 저장된 mnist 데이터를 읽어온다.
DATA_PATH = '/content/drive/MyDrive/Colab Notebooks/data/'
with open(DATA_PATH + 'mnist.pkl', 'rb') as f:
        mnist = pickle.load(f)

# mnist['data'] 숫자의 범위를 변환한다 (표준화) : 0 ~ 255 --> 0 ~ 1.0
# target = ['1', '2',...] 문자로 돼있음. --> 숫자로 변환해야 함.
x_feat = np.array(mnist['data']) / 255
y_target = np.array(mnist['target'].to_numpy().astype('int8')).reshape(-1,1)

# 학습 데이터와 시험 데이터를 생성한다.
x_train, x_test, y_train, y_test = train_test_split(x_feat, y_target, test_size=0.2)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

# 그래프 모델을 생성한다
n_hLayer = 1
n_hNeuron = 20
n_class = len(set(mnist['target']))

xInput = Input(batch_shape=(None, x_train.shape[1]), name='Input')
# xInput = Input(shape=(x_train.shape[1]), name='Input')
hLayer = Dense(n_hNeuron, activation='relu', name='Hidden_1')(xInput)

for i in range(n_hLayer - 1):
    hLayer = Dense(n_hNeuron, activation='relu', name='Hidden_' + str(i+2))(hLayer)

yOutput = Dense(n_class, activation='softmax', name='Output')(hLayer)

model = Model(xInput, yOutput)
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam')
model.summary()

hist = model.fit(x_train, y_train, 
                 batch_size=256, 
                 epochs=50, 
                 validation_data = (x_test, y_test))

# error가 감소하는 모습을 관찰한다.
plt.plot(hist.history['loss'], label='Train loss')
plt.plot(hist.history['val_loss'], label='Test loss')
plt.legend()
plt.title("Loss function")
plt.xlabel("epoch")
plt.ylabel("loss")
plt.show()

y_prob = model.predict(x_test)
y_pred = np.argmax(y_prob, axis=1).reshape(-1,1)
acc = (y_test == y_pred).mean()
print('정확도 ={:.4f}'.format(acc))

import pandas as pd
df = pd.DataFrame({'y_test': y_test.reshape(-1,), 'y_pred': y_pred.reshape(-1,)})
df.head(20)

