# -*- coding: utf-8 -*-
"""4-4.popcorn(countvector).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1udEgYeedSpM1hBeXUg2haRN7eiKQXh68
"""

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier
import pickle

DATA_PATH = '/content/drive/My Drive/Colab Notebooks/data/'

# 학습 데이터를 읽어온다.
with open(DATA_PATH + 'popcorn.pkl', 'rb') as f:
    x_text, _, y_target, _ = pickle.load(f)

vectorizer = CountVectorizer(analyzer="word", max_features=5000)
x_feat = vectorizer.fit_transform(x_text)

# 학습 데이터와 시험 데이터로 분리한다.
x_train, x_eval, y_train, y_eval = train_test_split(x_feat, y_target, test_size=0.2)
x_train.shape, x_eval.shape, y_train.shape, y_eval.shape

forest = RandomForestClassifier(n_estimators = 100)
forest.fit(x_train, y_train)

print('Accuracy: {:.4f}'.format(forest.score(x_eval, y_eval)))

