# -*- coding: utf-8 -*-
"""p59.CountVectorizer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WTKmcnbYw3VpyHtv-fD6wU_2JcWfwLm2
"""

from sklearn.feature_extraction.text import CountVectorizer

text_data = ['나는 배가 고프다', 
             '내일 점심 점심 뭐먹지',
             '내일 공부 해야겠다',
             '점심 먹고 공부 해야지']

count_vectorizer = CountVectorizer()
count_vectorizer.fit(text_data)
print(count_vectorizer.vocabulary_)

word2idx = count_vectorizer.vocabulary_
idx2word = {v:k for (k,v) in word2idx.items()}
word2idx

idx2word

sentence = [text_data[0]]
print(count_vectorizer.transform(sentence).toarray())

vec_1 = count_vectorizer.transform(sentence)
print(vec_1.toarray())

print(count_vectorizer.transform(text_data).toarray())

