# -*- coding: utf-8 -*-
"""4-2.popcorn(tfidf).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iwIx4UTagBLjeOd-WGCK6Hg9LFt8GbrJ
"""

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
import pickle

DATA_PATH = '/content/drive/My Drive/Colab Notebooks/data/'

# 학습 데이터를 읽어온다.
with open(DATA_PATH + 'popcorn.pkl', 'rb') as f:
    x_text, _, y_target, _ = pickle.load(f)

vectorizer = TfidfVectorizer(min_df=0.0, analyzer="char", sublinear_tf=True,
                             ngram_range=(1, 3), max_features=5000)
x_feat = vectorizer.fit_transform(x_text)

# 학습 데이터와 시험 데이터로 분리한다.
x_train, x_eval, y_train, y_eval = train_test_split(x_feat, y_target, test_size=0.2)
x_train.shape, x_eval.shape, y_train.shape, y_eval.shape

lgs = LogisticRegression(class_weight = 'balanced')
lgs.fit(x_train, y_train)

print('Accuracy: {:.4f}'.format(lgs.score(x_eval, y_eval)))

